---

extends: default

rules:
  document-start: disable
  line-length: disable
  indentation:
    indent-sequences: consistent

ignore:
- vendor/
- bootstrap/bootstrap-pod.yaml  # it is a go template file
